servicename = "userservice"
network = "tcp"
port = 80
allservices = []

[etcd]
endpoints = ["http://192.168.56.21:2379", "http://192.168.56.22:2379"]
dialtimeout = 30
dialkeepalivetime = 30

[logger]
filename = "/tmp/simple-game/log/%s-%s.log"
maxsize = 10
maxage = 30
maxbackups = 5
level = 0
compress = true
