apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-game-web
  namespace: simple-game
spec:
  replicas: 2
  selector:
    matchLabels:
      name: simple-game-web
  template:
    metadata:
      labels:
        name: simple-game-web
    spec:
      containers:
        - name: simple-game-web
          image: imxiejie/simple-game-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          volumeMounts:
            - name: log
              mountPath: /tmp/simple-game/log
            - name: time
              mountPath: /etc/localtime

      volumes:
        - name: log
          nfs:
            server: 192.168.56.22
            path: /mnt/log
        - name: time
          hostPath:
            path: /etc/localtime

---
apiVersion: v1
kind: Service
metadata:
  name: simple-game-web
  namespace: simple-game
spec:
  type: NodePort
  ports:
    - name: http
      port: 8088
      targetPort: 8088
      nodePort: 30000
  selector:
    name: simple-game-web
