apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-game-userservice
  namespace: simple-game
spec:
  replicas: 2
  selector:
    matchLabels:
      name: simple-game-userservice
  template:
    metadata:
      labels:
        name: simple-game-userservice
    spec:
      containers:
        - name: simple-game-userservice
          image: imxiejie/simple-game-userservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: time
              mountPath: /etc/localtime
          env:
            - name: color
              value: red
      volumes:
        - name: time
          hostPath:
            path: /etc/localtime

---
apiVersion: v1
kind: Service
metadata:
  name: simple-game-userservice
  namespace: simple-game
spec:
  clusterIP: None
  selector:
    name: simple-game-userservice
  ports:
    - port: 80
      targetPort: 80
