apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-game-userservice
  namespace: simple-game
spec:
  replicas: 2
  selector:
    matchLabels:
      name: simple-game-userservice
  template:
    metadata:
      labels:
        name: simple-game-userservice
    spec:
      containers:
        - name: simple-game-userservice
          image: imxiejie/simple-game-userservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: simple-game-userservice-service
  namespace: simple-game
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: grpc
