[web]
addr = "0.0.0.0"
port = 8088
proxies = ["0.0.0.0/0", "::/0"]
services = ["userservice"]
stack = true

[logger]
filedir = "/tmp/simple-game/log/%s-%s.log"
maxsize = 10
maxage = 30
maxbackups = 5
level = -1
compress = true

[etcd]
endpoints = ["http://192.168.56.21:2379", "http://192.168.56.22:2379"]
dialtimeout = 30
dialkeepalivetime = 30
